version: '3'
services:
    jwst: 
        build: .
        #command: /usr/locla/bin/notebook
        #command: conda activate jwst; jupyter notebook --allow-root --no-browser --ip=0.0.0.0
        #command: conda activate jwst; jupyter-lab --allow-root --no-browser --ip=0.0.0.0
        volumes: 
            - "./jwst:/jwst"
        ports: 
            - "8888:8888"
        environment:
            CRDS_PATH: /jwst/crds_cache
            CRDS_SERVER_URL: https://jwst-crds.stsci.edu
